language: node_js
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
 - "4.4.4"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: 
  - npm install
script:
  - npm run-script prod-build
  - npm test
